* Southern Ontario Stoke & Swell

This repository houses code for an experimental "conditions dashboard" for *whitewater river levels* and *surf spot wave forecasts* in southern Ontario. It draws data from various sources & presents it mostly in *line chart form* for quick checks of current conditions. The project is supposed to provide *a centralized spot to check forecasts*, but also *an opportunity for me to learn various newer web technologies*, so you shouldn't rely on it or expect any kind of data persistence at all, at least for the present.

* Feature List (user facing)

If the checkbox is ticked, then the feature has been implemented; if not, it's planned but doesn't work yet.

- *Rivers*
  - [-] river info tabs with the following info:
    - [X] current water levels w/ level quality estimate
    - [X] basic info about the river (route description)
    - [X] directions links for put-in and take-out
    - [ ] display map with all identified points (put-in, take-out, and other info such as alternate put-in/take-out, notable features, etc.)
    - [ ] weather forecast
    - [ ] links to recent radar/rainfall info (this will be tough to implement without some way to estimate river catchment areas, which is a bit of a big ask)
  - [ ] journalling: allow user to provide a brief journal entry, and optionally retrieve
    - [ ] historical gauge data
    - [ ] historical weather data
  - *Waves*
    - [ ] surf spot info tabs with the following info:
      - [ ] latest point forecast via GLOS wave/wind forecasts
      - [ ] spot description (wave info & quality in various wind/wave directions)
      - [ ] current buoy reading (if available)
      - [ ] direction links
      - [ ] windy forecast map link
      - [ ] GLOS forecast map link
    - [ ] journalling: allow user to provide a brief journal entry, and optionally retrieve
      - [ ] historical forecast data via GLOS
      - [ ] historical buoy data if available
      - [ ] historical weather data
  - *Both*
    - [ ] offline caching of data to allow use of charts when wifi fails.  
    - [ ] *DATA ATTRIBUTION* -- I haven't added this yet *at all* so please, if you're using the site, don't share widely -- I'm in copyright violation, or at least good-neighbour violation.  


* Data Sources

*ADD ATTRIBUTION*


* Contributions/Suggestions

*Please use the [[https://github.com/titaniumbones/river-levels/issues][Github Issues Tracker]]* for ideas/bug reports/improvements. Thanks!

* Technical Description

** TODO Describe Internal Data Structures (rivers, gauges, surf spots, etc)

** TODO Document JS code w/ js-doc

** TODO Describe technical roadmap
